cross_validation:
  kfold: 5
  output_variables:
  - consume
  testing_path: data/training.parquet
  training_path: data/training.parquet
display:
  show_plot: true
generate_plot: false
hyperparameter_search_space:
  batch_size:
    low: 16
    high: 246
  epochs:
    low: 10
    high: 270
  learning_rate:
    low: 0.0006760829753919819
    high: 0.1
  n_samples: 30
  optimizer_name:
    choices:
    - Adam
    type: categorical
loss_function:
  type: MSELoss
network:
  activation_functions:
    choices:
    - ReLU
    - Sigmoid
    - Tanh
  bias_initialization: zeros
  hidden_layers:
    low: 1
    high: 3
  hidden_neurons:
    low: 16
    high: 80
  weight_initialization: xavier_uniform
sampler:
  type: TPESampler
study:
  direction: minimize
targets:
  mre_threshold: 10.0
  nmae_target: 0.08
  r2_target: 0.99
variables:
  input_names: 'distance

    speed'
  output_names: consume
