sampler:
  type: TPESampler
study:
  direction: minimize
generate_plot: false
targets:
  r2_target: 0.99
  nmae_target: 0.08
  mre_threshold: 10.0
cross_validation:
  kfold: 5
loss_function:
  type: MSELoss
hyperparameter_search_space:
  n_samples: 10
  learning_rate:
    low: 0.01
    high: 0.1
  batch_size:
    low: 16
    high: 50
  epochs:
    low: 350
    high: 870
  optimizer_name:
    type: categorical
    choices:
    - Adam
network:
  hidden_layers:
    low: 2
    high: 3
  hidden_neurons:
    low: 42
    high: 127
  activation_functions:
    choices:
    - ReLU
    - Sigmoid
    - Tanh
  weight_initialization: xavier_uniform
  bias_initialization: zeros
data:
  training_path: data/training.parquet
  testing_path: data/training.parquet
  input_variables:
  - distance
  - speed
  output_variables:
  - consume
  train_ratio: 0.95
variables:
  input_names: 'distance

    speed'
  output_names: consume
display:
  show_plot: true
