cross_validation:
  kfold: 5
  test_split_ratio: 0.2
  output_variables:
  - consume
  testing_path: data/training.parquet
  training_path: data/training.parquet
  standardize_features: false
display:
  show_plot: false
  show_prediction_plot: true
  show_optuna_plots: true
generate_plot: false
hyperparameter_search_space:
  batch_size:
    low: 16
    high: 100
  epochs:
    low: 50
    high: 450
  learning_rate:
    low: 0.015848931924611134
    high: 0.1
  n_samples: 200
  optimizer_name:
    choices:
    - Adam
    type: categorical
loss_function:
  type: MSELoss
network:
  activation_functions:
    choices:
    - ReLU
  bias_initialization: zeros
  hidden_layers:
    low: 1
    high: 4
  hidden_neurons:
    low: 16
    high: 122
  weight_initialization: xavier_uniform
sampler:
  type: TPESampler
study:
  direction: minimize
targets:
  mre_threshold: 10.0
  nmae_target: 0.08
  r2_target: 0.99
variables:
  input_names: 'EVC_p_Offset

    relSpeed

    load

    EWG_p_Offset

    T_amb'
  output_names: FuelConsumption
