sampler:
  type: "TPESampler"

study:
  direction: "minimize"

generate_plot: false

targets:
  r2_target: 0.99
  nmae_target: 0.08
  mre_threshold: 25   # <-- use this variable in code

cross_validation:
  kfold: 5

loss_function:
  type: "MSELoss"

hyperparameter_search_space:
  n_samples: 25
  learning_rate:
    type: "loguniform"
    low: 0.0001
    high: 0.01
  batch_size:
    type: "int"
    low: 50
    high: 150
  epochs:
    type: "int"
    low: 200
    high: 200
  optimizer_name:
    type: "categorical"
    choices:
      - "Adam"
      # - "RMSprop"
      # - "SGD"

network:
  hidden_layers:
    type: "int"
    low: 1
    high: 2        
  hidden_neurons:
    type: "int"
    low: 4
    high: 30         
  activation_functions:
    choices:
      - "ReLU"
      - "Sigmoid"
      - "Tanh"
  weight_initialization: "xavier_uniform"  # currently used in code
  bias_initialization: "zeros"

data:
  training_path: "data/training.json"
  testing_path: "data/testing.json"
  input_variables: ['distance', 'speed', 'temp_outside', 'AC', 'rain']
  output_variables: ['consume']
  train_ratio: 0.95