sampler:
  type: TPESampler
study:
  direction: minimize
generate_plot: true
targets:
  r2_target: 0.99
  nmae_target: 0.08
  mre_threshold: 25.0
cross_validation:
  kfold: 5
loss_function:
  type: MSELoss
hyperparameter_search_space:
  n_samples: 30
  learning_rate:
    type: loguniform
    low: 0.001
    high: 0.1
  batch_size:
    type: int
    low: 50
    high: 150
  epochs:
    type: int
    low: 200
    high: 500
  optimizer_name:
    type: categorical
    choices:
    - Adam
network:
  hidden_layers:
    type: int
    low: 2
    high: 3
  hidden_neurons:
    type: int
    low: 64
    high: 128
  activation_functions:
    choices:
    - ReLU
    - Sigmoid
    - Tanh
  weight_initialization: xavier_uniform
  bias_initialization: zeros
data:
  training_path: data/training.json
  testing_path: data/testing.json
  input_variables:
  - distance
  - speed
  output_variables:
  - consume
  train_ratio: 0.95
variables:
  input_names: 'distance

    speed'
  output_names: consume
