sampler:
  type: "TPESampler"

study:
  direction: "minimize"

generate_plot: false

targets:
  r2_target: 0.99
  nmae_target: 0.08
  mre_threshold: 25   

cross_validation:
  kfold: 5

loss_function:
  type: "MSELoss"

hyperparameter_search_space:
  n_samples: 5
  learning_rate:
    type: "loguniform"
    low: 0.0001
    high: 0.01
  batch_size:
    type: "int"
    low: 50
    high: 150
  epochs:
    type: "int"
    low: 200
    high: 200
  optimizer_name:
    type: "categorical"
    choices:
      - "Adam"
      # - "RMSprop"
      # - "SGD"

network:
  hidden_layers:
    type: "int"
    low: 1
    high: 2        
  hidden_neurons:
    type: "int"
    low: 4
    high: 30         
  activation_functions:
    choices:
      - "ReLU"
      - "Sigmoid"
      - "Tanh"
  weight_initialization: "xavier_uniform" 
  bias_initialization: "zeros"

data:
  training_path: "data/train.csv"
  testing_path: "data/test.csv"
  input_variables: [
    'x805','x807','x334','x478','x254','x133','x196','x584','x199','x465',
    'x547','x154','x32','x546','x352','x29','x72','x230','x436','x602',
    'x760','x424','x180','x453','x686','x410','x2','x151','x231','x315',
    'x319','x8','x528','x179','x437','x22','x639','x310','x668','x594',
    'x63','x740','x388','x69','x831','x538','x822','x819','x349','x398',
    'x370','x593','x220','x671','x40','x97','x82','x56','x613','x399',
    'x194','x773','x720','x119','x703','x577','x564','x827','x27','x621',
    'x181','x28','x824','x107','x455','x688','x582','x672','x270','x190',
    'x371','x381','x367','x279','x526','x758','x105','x770','x213','x692',
    'x610','x422','x292','x20','x189','x783','x374','x414','x84','x402',
    'x537','x531','x34','x585','x559','x117','x778','x782','x23','x700',
    'x288','x731','x479','x641','x16','x284','x295','x173','x88','x15',
    'x278','x439','x64','x350','x419','x87','x784','x395','x385','x714',
    'x342','x485','x113','x562','x814','x136','x209','x810','x659','x675',
    'x572','x396','x5','x333','x165','x483','x660','x442','x491','x456',
    'x163','x98','x94','x211','x648','x407','x66','x403','x346','x262',
    'x99','x408','x684','x246','x504','x451','x65','x120','x252','x379',
    'x630','x608','x769','x141','x589','x759','x240','x157','x498','x542',
    'x121','x820','x110','x771','x614','x727','x646','x55','x811','x477',
    'x148','x635','x285','x123','x470','x475','x734','x75','x721']
  output_variables: ['y']
  train_ratio: 0.95