sampler:
  type: "TPESampler"

study:
  direction: "minimize"

generate_plot: false

targets:
  r2_target: 0.99
  nmae_target: 0.08
  mre_threshold: 25   

cross_validation:
  kfold: 5

loss_function:
  type: "MSELoss"

hyperparameter_search_space:
  n_samples: 2
  learning_rate:
    type: "loguniform"
    low: 0.0001
    high: 0.01
  batch_size:
    type: "int"
    low: 50
    high: 150
  epochs:
    type: "int"
    low: 200
    high: 200
  optimizer_name:
    type: "categorical"
    choices:
      - "Adam"
      # - "RMSprop"
      # - "SGD"

network:
  hidden_layers:
    type: "int"
    low: 1
    high: 2        
  hidden_neurons:
    type: "int"
    low: 4
    high: 30         
  activation_functions:
    choices:
      - "ReLU"
      - "Sigmoid"
      - "Tanh"
  weight_initialization: "xavier_uniform" 
  bias_initialization: "zeros"

data:
  training_path: "data/test.csv"
  testing_path: "data/test.csv"
  input_variables: ['Area Code', 'Months Code', 'Element Code', 'Y1961', 'Y1962']
  output_variables: ['Y1963']
  train_ratio: 0.95